[package]
name = "ledit"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.6"
tui = "0.15.0"
uuid = {version = "0.8.2", features = ["v4"]}