[theme]
status_bar_background = "#0000ff"
status_bar_foreground = "#FFFFFF"
explorer_background = "#000000"
explorer_selected_background = "#808080"
explorer_selected_foreground = "#000000"
explorer_directory_foreground = "#00FF00"
explorer_file_foreground = "#0000FF"
explorer_info_foreground = "#808080"
active_view_border = "#0084FF"
view_border = "#FFFFFF"
editor_background = "#000000"
commands_view_background = "#000000"
commands_view_foreground = "#FFFFFF"
explorer_hidden_foreground = "#808080"
app_background = "#000000"
app_foreground = "#0000FF"
status_error = "#FF0000"
status_warning = "FF9100"
status_info = "#00FF00"