[theme]
status_bar_background = "#FF0000"
status_bar_foreground = "#FFFFFF"
explorer_background = "#000000"
explorer_selected_background = "#FF0000"
explorer_selected_foreground = "#FFFFFF"
explorer_directory_foreground = "#00FF00"
explorer_file_foreground = "#FF0000"
explorer_info_foreground = "#808080"
active_view_border = "#FF0000"
view_border = "#FFFFFF"
editor_background = "#000000"
commands_view_background = "#000000"
commands_view_foreground = "#FFFFFF"
explorer_hidden_foreground = "#808080"
app_background = "#000000"
app_foreground = "#FF0000"
status_error = "#660000"
status_warning = "#FFF200"
status_info = "#00FF00"